# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal

# Profile
profile:
  # Your profile picture
  avatar: "avatar.jpg"
  
  # Your details
  first_name: Faranak
  last_name: Rajabi
  role: PhD Candidate in Mechanical Engineering
  
  # Organizations
  organizations:
    - name: University of California, Santa Barbara
      url: https://www.ucsb.edu/
  
  social:
    - icon: envelope
      icon_pack: fas
      link: 'mailto:faranakrajabi@ucsb.edu'
    - icon: github
      icon_pack: fab
      link: https://github.com/faranakR
    - icon: linkedin
      icon_pack: fab
      link: your-linkedin-url
    - icon: google-scholar
      icon_pack: ai
      link: your-google-scholar-url
    - icon: researchgate
      icon_pack: ai
      link: your-researchgate-url

# Site Features
features:
  repository:
    url: 'https://github.com/faranakR/faranakrajabi'
    content_dir: content
    branch: main